#!/bin/bash

# Author: William Z Chadwick
# Date Created: 08/06/2022
# Date Modified:
# Description: Combines the two commands, "cd" and "ls -a". This seemed necessary because it wasn't possible to use the same things as an alias - apparently?
# Usage: clds

#

cd read && /
ls -a

exit 0

# Well, so far, after a number of changes, this script doesn't work, but only shows items from the home directory. What does that mean? That cd isn't accepting input before the ls-a command runs?
