#!/bin/bash

# Author: William Z Chadwick
# Date Created: 08/06/2022
# Date Modified:
# Description: Combines the two commands, "cd" and "ls -a". Current cmd makeup helpfully suggested by Sara Kuenzi for ZSH; we'll see if it will work for bash.
# Usage: clds

cd /$1 && ls -a
exit 0

# old code attempts:
# realpath was suggested, how do I use it?
# read -p "Enter your path:" input
# cd $input ls -a
