#!/bin/bash

# Author: William Z Chadwick
# Date Created: 08/06/2022
# Date Modified:
# Description: Combines the two commands, "cd" and "ls -a". This seemed necessary because it wasn't possible to use the same things as an alias - apparently?
# Usage: clds


# realpath was suggested, how do I use it?

read -p "Enter your path:" input
cd $input &&
ls -a

exit 0

# I think I fixed one of the bugs; but now it won't take me back to ~/ hum hum
